def can_build(env, platform):
    env.module_add_dependencies("grit", ["gdscript"])
    return True


def configure(env):
    pass


def get_opts(platform):
    from SCons.Variables import BoolVariable, PathVariable

    return [
        BoolVariable(
            "grit_conformance",
            "Always activate generated code, used to run the GDScript test suite natively",
            False,
        ),
        PathVariable(
            "grit_generated",
            "Directory containing the C++ sources generated by Grit",
            "",
            PathVariable.PathAccept,
        ),
    ]
